apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "install.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy: { type: Recreate }
  selector:
    matchLabels:
      {{- include "install.crunchyLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "install.crunchyLabels" . | nindent 8 }}
    spec:
      nodeSelector:
        sapian-k3s-role: server
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
      - name: operator
        image: "{{ .Values.image.image }}"
        env:
        - name: CRUNCHY_DEBUG
          value: {{ if eq .Values.debug false  }}"false"{{- else }}"true"{{- end }}
        {{- range  $image_name, $image_val := .Values.relatedImages }}
        - name: RELATED_IMAGE_{{ $image_name | upper }}
          value: "{{ $image_val.image }}"
        {{- end }}
        {{- if .Values.singleNamespace }}
        - name: PGO_TARGET_NAMESPACE
          valueFrom: { fieldRef: { apiVersion: v1, fieldPath: metadata.namespace } }
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
      serviceAccount: {{ include "install.serviceAccountName" . }}
